# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LfrCli < Formula
  desc "LFR is an unofficial tool written in Go that helps you create & manage your Liferay projects."
  homepage "https://github.com/lgdd/lfr-cli"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/lfr-cli/releases/download/v2.0.0/lfr-cli_2.0.0_darwin_amd64.tar.gz"
      sha256 "82b44e825d2caf47345cae3cde7c60d54f704eea023f4a84f4c41c03b9f0bebe"

      def install
        bin.install "lfr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/lfr-cli/releases/download/v2.0.0/lfr-cli_2.0.0_darwin_arm64.tar.gz"
      sha256 "26b5b75310ec320ba1b70d289eab751528ceb996cf26b7a6b297f286fd523a59"

      def install
        bin.install "lfr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/lfr-cli/releases/download/v2.0.0/lfr-cli_2.0.0_linux_amd64.tar.gz"
      sha256 "dfdf9e32740fd0318bfae92d21b49716ad5068c107f5e12d5e6ab0d1abb4c26b"

      def install
        bin.install "lfr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/lfr-cli/releases/download/v2.0.0/lfr-cli_2.0.0_linux_arm64.tar.gz"
      sha256 "69148c3e107830324a0ae2db9e6cf4de98462cfdfb33428d736689c9966e43bc"

      def install
        bin.install "lfr"
      end
    end
  end
end
