# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LfrCli < Formula
  desc "LFR is an unofficial tool written in Go that helps you create & manage your Liferay projects."
  homepage "https://github.com/lgdd/lfr-cli"
  version "3.2.0"

  on_macos do
    on_intel do
      url "https://github.com/lgdd/lfr-cli/releases/download/v3.2.0/lfr-cli_3.2.0_darwin_amd64.tar.gz"
      sha256 "04edcf6000c18c985661837bbdcc441075dc04264e5a44710189069b84409a76"

      def install
        bin.install "lfr"
      end
    end
    on_arm do
      url "https://github.com/lgdd/lfr-cli/releases/download/v3.2.0/lfr-cli_3.2.0_darwin_arm64.tar.gz"
      sha256 "b41fc875cb38174d9564e27f340374bba6ad3cba135d4306b7830826663d4fe5"

      def install
        bin.install "lfr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lgdd/lfr-cli/releases/download/v3.2.0/lfr-cli_3.2.0_linux_amd64.tar.gz"
        sha256 "2bd5ea251579a06b34de71fb90ea691e3de387a7ea61ce83286c65ceb5c9e030"

        def install
          bin.install "lfr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lgdd/lfr-cli/releases/download/v3.2.0/lfr-cli_3.2.0_linux_arm64.tar.gz"
        sha256 "e08109c4e9ab068d4152301c87632831825b08b53a9bdf91df02e9b8fe79a93e"

        def install
          bin.install "lfr"
        end
      end
    end
  end
end
