# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LfrCli < Formula
  desc "LFR is an unofficial tool written in Go that helps you create & manage your Liferay projects."
  homepage "https://github.com/lgdd/lfr-cli"
  version "3.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/lfr-cli/releases/download/v3.0.0/lfr-cli_3.0.0_darwin_amd64.tar.gz"
      sha256 "70ff7bf044ba67483990fc3567369627f0944537789723055ad890970da23811"

      def install
        bin.install "lfr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/lfr-cli/releases/download/v3.0.0/lfr-cli_3.0.0_darwin_arm64.tar.gz"
      sha256 "58ed1fd3a1ae30d357bae590f8c6a30e26935c1b82d38354420a267aeee3e3f6"

      def install
        bin.install "lfr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/lfr-cli/releases/download/v3.0.0/lfr-cli_3.0.0_linux_amd64.tar.gz"
      sha256 "b47aa289ebed5f30a3655a0c38e35d4ca3909b78d8a7fbac9337c018d99faa04"

      def install
        bin.install "lfr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/lfr-cli/releases/download/v3.0.0/lfr-cli_3.0.0_linux_arm64.tar.gz"
      sha256 "34a0410b41112237ce01b66bdfb9c8e9de65996c19ffe1f54e47f8973f0be1d2"

      def install
        bin.install "lfr"
      end
    end
  end
end
