# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LiferayCli < Formula
  desc "Liferay CLI (lfr) is an unofficial tool written in Go that helps you create & manage your Liferay projects."
  homepage "https://github.com/lgdd/liferay-cli"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/liferay-cli/releases/download/v1.2.0/liferay-cli_1.2.0_darwin_amd64.tar.gz"
      sha256 "ff06de9136393ae5c75b2a5f76f5fe578089f4cbb5a9623c57b7278ac75f0342"

      def install
        bin.install "lfr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/liferay-cli/releases/download/v1.2.0/liferay-cli_1.2.0_darwin_arm64.tar.gz"
      sha256 "204daee87cb698130f7ab4e4beeee6551dd3685e0a19e2d7cc522c22b869c679"

      def install
        bin.install "lfr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/liferay-cli/releases/download/v1.2.0/liferay-cli_1.2.0_linux_arm64.tar.gz"
      sha256 "19bd5efc533e2f919ec263eff13096ee673368fafc7568e1bb05f6649b4db555"

      def install
        bin.install "lfr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/liferay-cli/releases/download/v1.2.0/liferay-cli_1.2.0_linux_amd64.tar.gz"
      sha256 "7427ea17b19550dc2f9f86bb27a9f1fd8fcc4be5ba882da8239b4908c23bbad2"

      def install
        bin.install "lfr"
      end
    end
  end
end
