# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LiferayCli < Formula
  desc "Liferay CLI (lfr) is an unofficial tool written in Go that helps you create & manage your Liferay projects."
  homepage "https://github.com/lgdd/liferay-cli"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lgdd/liferay-cli/releases/download/v1.4.0/liferay-cli_1.4.0_darwin_arm64.tar.gz"
      sha256 "5546762ca200978e0441e901a897df51e83610811135f4042270884ef2ababc4"

      def install
        bin.install "lfr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/liferay-cli/releases/download/v1.4.0/liferay-cli_1.4.0_darwin_amd64.tar.gz"
      sha256 "a469a748ff917a6f4c0e0d5d2d8be35d2cbadbd1a5302ea50970dd7716f5958b"

      def install
        bin.install "lfr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lgdd/liferay-cli/releases/download/v1.4.0/liferay-cli_1.4.0_linux_amd64.tar.gz"
      sha256 "9c18ddcb8f3ca4a98adb1977273c5862b2ead064c66d2354b98ac06fe4ab3e69"

      def install
        bin.install "lfr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgdd/liferay-cli/releases/download/v1.4.0/liferay-cli_1.4.0_linux_arm64.tar.gz"
      sha256 "800f96e425878c03b57653daba2855857172c89344f50973451012d798ff56ee"

      def install
        bin.install "lfr"
      end
    end
  end
end
